name: Configure Infrastructure
on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
    inputs:
      public_ip:
        required: true
        type: string
jobs:
  ansible:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt install -y ansible

      - name: Add SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Generate inventory file
        run: |
          echo "[minecraft]" > inventory.ini
          echo "${{ inputs.public_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=./id_rsa" >> inventory.ini

      - name: Run Ansible Playbook
        run: ansible-playbook minecraft.yaml -i inventory.ini

