name: Configure Infrastructure
on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
    inputs:
      public_ip:
        required: true
        type: string
jobs:
  ansible:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts and setup ssh key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ inputs.public_ip }} >> ~/.ssh/known_hosts

      - name: Generate inventory file
        run: |
          echo "[minecraft]" > inventory.ini
          echo "${{ inputs.public_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini

      - name: Run Ansible Playbook
        run: ansible-playbook minecraft.yaml -i inventory.ini

