name: Provision Infrastructure
on:
  workflow_call:
    secrets:
      SSH_PUBLIC_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false
      AWS_REGION:
        required: true
    outputs:
      public_ip:
        description: "The IP for the provisioned server"
        value: ${{ jobs.terraform.outputs.public_ip }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    outputs:
      public_ip: ${{ steps.output_ip.outputs.public_ip }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Add SSH public key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var 'key_path=~/.ssh/id_rsa.pub'

      - name: Terraform Apply
        run: terraform apply -var 'key_path=~/.ssh/id_rsa.pub' -auto-approve

      - name: Get Public IP
        id: output_ip
        run: |
          ip=$(terraform output -raw minecraft_server_ip)
          echo "public_ip=$ip" >> $GITHUB_OUTPUT
