name: Provision Infrastructure
on:
  workflow_call:
    inputs:
      public-key:
        required: true
        type: string
      aws-access-key-id:
        required: true
        type: string
      aws-secret-access-key:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      aws-session-token:
        required: false
        type: string
    outputs:
      public-ip:
        description: "The IP for the provisioned minecraft server"
        value: ${{ jobs.terraform.outputs.public-ip }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Add SSH public key from secret
        run: |
          echo "${{ inputs.public-key }}" > id_rsa.pub
          chmod 600 id_rsa.pub

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-session-token: ${{ inputs.aws-session-token }}
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var 'key_path=./id_rsa.pub'

      - name: Terraform Apply
        run: terraform apply -var 'key_path=./id_rsa.pub' -auto-approve

      - name: Get Public IP
        id: output-ip
        run: |
          ip=$(terraform output -raw minecraft_server_ip)
          echo "public-ip=$ip" >> $GITHUB_OUTPUT
