name: Standup Infrastructure on Push
on:
  push:
    branches:
      - main
jobs:
  provision:
    uses: ./.github/workflows/provision.yaml
    secrets:
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  configure:
    needs: provision
    uses: ./.github/workflows/configure.yaml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      public_ip: ${{ needs.provision.outputs.public_ip }}
